// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {main} from '../models';

export function AddCategory(arg1:dtos.CategoryCreate):Promise<void>;

export function AddGoal(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<number>;

export function AddRule(arg1:dtos.RuleCreate):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteEvent(arg1:number):Promise<void>;

export function DeleteGoal(arg1:number):Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function DisableTracking():Promise<void>;

export function EnableTracking():Promise<void>;

export function ForceCleanup():Promise<void>;

export function GetActivityCalendar(arg1:number):Promise<Array<dtos.DayActivity>>;

export function GetAppUsageData(arg1:string):Promise<Array<dtos.AppUsageItem>>;

export function GetCategories():Promise<Array<dtos.CategoryListItem>>;

export function GetCategory(arg1:number):Promise<dtos.CategoryDetail>;

export function GetCategoryUsageData(arg1:string):Promise<Array<dtos.CategoryUsageItem>>;

export function GetCategoryUsageRange(arg1:string,arg2:string):Promise<Array<dtos.DailyCategorySummary>>;

export function GetCategoryUsageTotals(arg1:string,arg2:string):Promise<Array<dtos.CategoryUsageItem>>;

export function GetEventLog(arg1:string):Promise<Array<dtos.EventLogItem>>;

export function GetGoals():Promise<Array<dtos.GoalItem>>;

export function GetPreferences():Promise<dtos.PreferencesDto>;

export function GetRerunJobStatus():Promise<main.RerunJobStatusDTO>;

export function GetRule(arg1:number):Promise<dtos.RuleDetail>;

export function GetRules():Promise<Array<dtos.RuleListItem>>;

export function GetUncategorizedApps(arg1:string):Promise<Array<string>>;

export function IsTrackingEnabled():Promise<boolean>;

export function OverrideEventCategory(arg1:number,arg2:number):Promise<void>;

export function SavePreferences(arg1:dtos.PreferencesDto):Promise<void>;

export function StartRerunRules(arg1:string,arg2:string):Promise<void>;

export function TestRuleMatch(arg1:string,arg2:string,arg3:string):Promise<dtos.RuleMatchResult>;

export function UpdateCategory(arg1:number,arg2:dtos.CategoryUpdate):Promise<void>;

export function UpdateGoal(arg1:number,arg2:string,arg3:Array<number>,arg4:number,arg5:number,arg6:boolean):Promise<void>;

export function UpdateRule(arg1:number,arg2:dtos.RuleUpdate):Promise<void>;
