// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DisableTracking() {
  return window['go']['main']['App']['DisableTracking']();
}

export function EnableTracking() {
  return window['go']['main']['App']['EnableTracking']();
}

export function ForceCleanup() {
  return window['go']['main']['App']['ForceCleanup']();
}

export function GetActivityCalendar(arg1) {
  return window['go']['main']['App']['GetActivityCalendar'](arg1);
}

export function GetAppUsageData(arg1) {
  return window['go']['main']['App']['GetAppUsageData'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetCategoryUsageData(arg1) {
  return window['go']['main']['App']['GetCategoryUsageData'](arg1);
}

export function GetCategoryUsageRange(arg1, arg2) {
  return window['go']['main']['App']['GetCategoryUsageRange'](arg1, arg2);
}

export function GetEventLog(arg1) {
  return window['go']['main']['App']['GetEventLog'](arg1);
}

export function GetGoals() {
  return window['go']['main']['App']['GetGoals']();
}

export function GetRule(arg1) {
  return window['go']['main']['App']['GetRule'](arg1);
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetUncategorizedApps(arg1) {
  return window['go']['main']['App']['GetUncategorizedApps'](arg1);
}

export function IsTrackingEnabled() {
  return window['go']['main']['App']['IsTrackingEnabled']();
}

export function SetGoal(arg1, arg2) {
  return window['go']['main']['App']['SetGoal'](arg1, arg2);
}

export function TestRuleMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestRuleMatch'](arg1, arg2, arg3);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateRule'](arg1, arg2);
}
