// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DisableTracking() {
  return window['go']['main']['App']['DisableTracking']();
}

export function EnableTracking() {
  return window['go']['main']['App']['EnableTracking']();
}

export function ForceCleanup() {
  return window['go']['main']['App']['ForceCleanup']();
}

export function GetAppUsageData(arg1) {
  return window['go']['main']['App']['GetAppUsageData'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetCategoryUsageData(arg1) {
  return window['go']['main']['App']['GetCategoryUsageData'](arg1);
}

export function GetRule(arg1) {
  return window['go']['main']['App']['GetRule'](arg1);
}

export function GetRules(arg1) {
  return window['go']['main']['App']['GetRules'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTrackingEnabled() {
  return window['go']['main']['App']['IsTrackingEnabled']();
}
