// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {models} from '../models';

export function AddCategory(arg1:dtos.CategoryCreate):Promise<void>;

export function AddRule(arg1:dtos.RuleCreate):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function DisableTracking():Promise<void>;

export function EnableTracking():Promise<void>;

export function ForceCleanup():Promise<void>;

export function GetAppUsageData(arg1:string):Promise<Array<models.AppAggregation>>;

export function GetCategories():Promise<Array<dtos.CategoryListItem>>;

export function GetCategory(arg1:number):Promise<dtos.CategoryDetail>;

export function GetCategoryUsageData(arg1:string):Promise<any>;

export function GetRule(arg1:number):Promise<dtos.RuleDetail>;

export function GetRules():Promise<Array<dtos.RuleListItem>>;

export function IsTrackingEnabled():Promise<boolean>;

export function UpdateCategory(arg1:number,arg2:dtos.CategoryUpdate):Promise<void>;

export function UpdateRule(arg1:number,arg2:dtos.RuleUpdate):Promise<void>;
