// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableTracking() {
  return window['go']['main']['App']['DisableTracking']();
}

export function EnableTracking() {
  return window['go']['main']['App']['EnableTracking']();
}

export function ForceCleanup() {
  return window['go']['main']['App']['ForceCleanup']();
}

export function GetAppUsageData(arg1) {
  return window['go']['main']['App']['GetAppUsageData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTrackingEnabled() {
  return window['go']['main']['App']['IsTrackingEnabled']();
}
